name: Test 2048 Game

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install any future dependencies here
        # pip install -r requirements.txt
    
    - name: Test game logic
      run: |
        python test_2048_logic.py
    
    - name: Test game import
      run: |
        python -c "from game_2048 import Game2048Logic, Game2048GUI; print('Import successful')"
    
    - name: Check code syntax
      run: |
        python -m py_compile game_2048.py
        python -m py_compile play_2048.py
        python -m py_compile test_2048_logic.py
